tap "eugenmayer/dockersync"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/bundle"
tap "homebrew/services"
tap "go-delve/delve"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/cask"
tap "vitorgalvao/tiny-scripts"
cask "java"
brew "antigen"
brew "asciinema"
brew "aspell", args: ["with-lang-nl"]
brew "autoconf"
brew "gettext"
brew "libffi"
brew "cairo"
brew "composer"
brew "go"
brew "dep"
brew "dnsmasq", restart_service: true
brew "docker-machine", link: false
brew "doxygen"
brew "emacs"
brew "fswatch"
brew "gd"
brew "ghostscript"
brew "git"
brew "gobject-introspection"
brew "gradle"
brew "libtool"
brew "graphviz", args: ["with-pango"]
brew "highlight"
brew "hr"
brew "httpie"
brew "hub"
brew "imagemagick", args: ["with-ghostscript"]
brew "libevent"
brew "libgit2"
brew "libxml2"
brew "libyaml"
brew "mackup"
brew "mas"
brew "maven"
brew "mhash"
brew "mcrypt"
brew "mono"
brew "mysql"
brew "nginx", restart_service: true
brew "nmap"
brew "node"
brew "openjpeg"
brew "poppler"
brew "pdf2svg"
brew "unixodbc"
brew "php", restart_service: true
brew "php@5.6", restart_service: true
brew "php@7.0", restart_service: true, link: true
brew "phpunit"
brew "plantuml"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rsync"
brew "ruby"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "unison"
brew "utf8proc"
brew "watch"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "eugenmayer/dockersync/unox"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "alfred"
cask "android-platform-tools"
cask "android-studio"
cask "battle-net"
cask "brave"
cask "calibre"
cask "cleanmymac"
cask "dash"
cask "discord"
cask "docker"
cask "dotnet"
cask "dropbox"
cask "etcher"
cask "firefox"
cask "fluid"
cask "flux"
cask "forklift"
cask "freac"
cask "ghost"
cask "google-chrome"
cask "hyper"
cask "iterm2"
cask "jetbrains-toolbox"
cask "launchcontrol"
cask "microsoft-office"
cask "mysqlworkbench"
cask "navicat-for-mysql"
cask "ngrok"
cask "nylas-mail"
cask "obs"
cask "origin"
cask "paw"
cask "phpstorm"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "reggy"
cask "sequel-pro"
cask "signal"
cask "sketch"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "stretchly"
cask "sublime-text"
cask "teamviewer"
cask "tunnelblick"
cask "twitch"
cask "vagrant"
cask "virtualbox"
cask "vnc-viewer"
cask "webpquicklook"
cask "whatsapp"
cask "zeplin"
cask "caskroom/fonts/font-fira-code"
cask "caskroom/fonts/font-fontawesome"
cask "caskroom/fonts/font-hack"
cask "caskroom/fonts/font-lato"
cask "caskroom/fonts/font-roboto"
cask "caskroom/fonts/font-ubuntu"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
